# Generated by Django 3.2.3 on 2021-05-21 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Comment', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('subject', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Background_Image', models.ImageField(upload_to='')),
                ('Subheading1', models.CharField(blank=True, max_length=100, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('Paragraph1', models.TextField(blank=True, null=True)),
                ('Subheading2', models.CharField(blank=True, max_length=100, null=True)),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Paragraph2', models.TextField(blank=True, null=True)),
                ('Subheading3', models.CharField(blank=True, max_length=100, null=True)),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Paragraph3', models.TextField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Video', models.FileField(blank=True, null=True, upload_to='Videos')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('coments', models.ManyToManyField(blank=True, to='Blog.Comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
