# Generated by Django 3.2.3 on 2021-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='Paragraph1',
        ),
        migrations.AddField(
            model_name='blog',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Mode',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
