# Generated by Django 3.2.3 on 2021-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210522_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=models.TextField(),
        ),
    ]
